locale: "pl"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/content/portfolio"
    create: true
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data publikacji", name: "date", widget: "datetime" }
      - { label: "Zdjęcie", name: "thumbnail", widget: "image" }
      - { label: "Treść", name: "body", widget: "markdown" }

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# when using the default proxy server port
local_backend: true
backend:
  name: git-gateway
